### PR TITLE
fix: use `ConvertInterfaceLuidToIndex` to obtain the index

### LINKED ISSUE #21: win8  get_adapter_index  err Unable to find matching

### PR DESCRIPTION
**Pull request by thomaseizinger**
Supersedes: #26
Resolves: #21

### CODE REVIEW

File: src/ffi.rs [hunk 1]
```diff
@@ -0,0 +1,43 @@
+use crate::wintun_raw::WCHAR;
```
Comment (TroyNeubauer) [inline src/ffi.rs:1]: I like the structure here

**Review by TroyNeubauer — APPROVED** [review]
Nice!
